# Generated by Django 4.1.6 on 2023-04-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0008_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
